[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x94992ee6e22ff194ffa60c36960bfeddcacb22ec19f42150f6e3384dc5b48a"
transaction_hash = "0x1c672e89fb91b6f5809350739fdbda9c10c63411e813e2de4fd06e88421cec7"
block_number = 3
seed = "camini"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4ae4a35af8843b5efc8c4485b8d553cd933f28ec8ba3b7f64b0f0ef1909252d"
class_hash = "0x26212a425fb0f71c5b832e4485e7736b53ec6e256ccc8d519ccd9da414c84eb"
original_class_hash = "0x26212a425fb0f71c5b832e4485e7736b53ec6e256ccc8d519ccd9da414c84eb"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-a-2fed5b94.json"
reads = []
writes = []
init_calldata = []
tag = "ok-a"
systems = []
manifest_name = "ok-a-2fed5b94"

[[contracts]]
kind = "DojoContract"
address = "0x6507931819ffd80cbf9de89685653750e6f38b89725129f7bdfe0b59275c04c"
class_hash = "0x45e66dfbba1182f1ec00e09041ad2478fc0c06bdf759f360ee2d4c2e58c4726"
original_class_hash = "0x45e66dfbba1182f1ec00e09041ad2478fc0c06bdf759f360ee2d4c2e58c4726"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-arena-69309f5d.json"
reads = []
writes = [
    "ok-Game",
    "ok-Position",
    "ok-Global",
    "ok-Tile",
    "ok-Piece",
]
init_calldata = []
tag = "ok-arena"
systems = [
    "move",
    "attack",
]
manifest_name = "ok-arena-69309f5d"

[[contracts]]
kind = "DojoContract"
address = "0x30864520b611472cc5adb0376fd8437c2e9716f7957de0e8a5bd3c97bfb1b41"
class_hash = "0x796677ad9d5c592fc6c686ca21f8fe26b9f06fd31318ed4067f44fe800a79d8"
original_class_hash = "0x796677ad9d5c592fc6c686ca21f8fe26b9f06fd31318ed4067f44fe800a79d8"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-b-4ebf424d.json"
reads = []
writes = []
init_calldata = []
tag = "ok-b"
systems = []
manifest_name = "ok-b-4ebf424d"

[[contracts]]
kind = "DojoContract"
address = "0x2c1cfdd4e63c1b775f18afc2dc18f9a212e86049551560cdf09c29545b1fe96"
class_hash = "0x3550db90d908e7ca8e39368f1558080a26d672046b6fc4358aa4231e391c44b"
original_class_hash = "0x3550db90d908e7ca8e39368f1558080a26d672046b6fc4358aa4231e391c44b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-damage-4ffd3b4e.json"
reads = []
writes = [
    "ok-Tile",
    "ok-Piece",
    "ok-DamageAmt",
]
init_calldata = []
tag = "ok-damage"
systems = ["set_amt"]
manifest_name = "ok-damage-4ffd3b4e"

[[contracts]]
kind = "DojoContract"
address = "0x373e4caebf565e9ae21ff53161dfd85940885b21afcfbf445979b558ad9cb3a"
class_hash = "0x40b0ca5e9cb980a46c5779fd48c4c8d0aa05a63c7f315790713497bc1897548"
original_class_hash = "0x40b0ca5e9cb980a46c5779fd48c4c8d0aa05a63c7f315790713497bc1897548"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-gacha-25121cda.json"
reads = []
writes = [
    "ok-Piece",
    "ok-Player",
]
init_calldata = []
tag = "ok-gacha"
systems = []
manifest_name = "ok-gacha-25121cda"

[[contracts]]
kind = "DojoContract"
address = "0xff65a401ff4f5f3c81a78b797b84e9a9aff017373fb5236796fca97c4b90e"
class_hash = "0x169940e0549934076f738a6558ba63cd48ac376329e553f8606673da1f200b"
original_class_hash = "0x169940e0549934076f738a6558ba63cd48ac376329e553f8606673da1f200b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-gov-3de021f4.json"
reads = []
writes = [
    "ok-PieceType",
    "ok-Global",
    "ok-Effect",
    "ok-Pool",
]
init_calldata = []
tag = "ok-gov"
systems = [
    "add_piece",
    "set_damage_contract",
    "add_effect",
]
manifest_name = "ok-gov-3de021f4"

[[contracts]]
kind = "DojoContract"
address = "0x50d47e1ea57f4cac383ee7a5ef53438c6162f4f4f82063ca397be26c094438"
class_hash = "0x2904810f841c4232cb6b8af606e89b54b8397be7746c8aaf54a569584a81c"
original_class_hash = "0x2904810f841c4232cb6b8af606e89b54b8397be7746c8aaf54a569584a81c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-matchmaking-7ba13579.json"
reads = []
writes = [
    "ok-Global",
    "ok-Team",
    "ok-Player",
    "ok-Piece",
    "ok-Tile",
    "ok-Position",
]
init_calldata = []
tag = "ok-matchmaking"
systems = [
    "join_game",
    "start_game",
]
manifest_name = "ok-matchmaking-7ba13579"

[[contracts]]
kind = "DojoContract"
address = "0x734f465455d09ec361b1bab3102b8d2c9d77be3b9adf999eda753236d0490a2"
class_hash = "0x683bb297ec1c94d31f47114247f9a9398f672444da8286ece0530975bfb5731"
original_class_hash = "0x683bb297ec1c94d31f47114247f9a9398f672444da8286ece0530975bfb5731"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-teambuilder-5d16e22b.json"
reads = []
writes = [
    "ok-Team",
    "ok-Player",
    "ok-Piece",
    "ok-Tile",
    "ok-Position",
]
init_calldata = []
tag = "ok-teambuilder"
systems = [
    "add_piece_to_team",
    "remove_piece_from_team",
]
manifest_name = "ok-teambuilder-5d16e22b"

[[models]]
kind = "DojoModel"
class_hash = "0x5a971d3e8643648741e57e05681cd27ce2e6a33a6d081f6c3e9c91b10f7bf75"
original_class_hash = "0x5a971d3e8643648741e57e05681cd27ce2e6a33a6d081f6c3e9c91b10f7bf75"
abi = "manifests/dev/deployment/abis/models/ok-DamageAmt-1b34a805.json"
tag = "ok-DamageAmt"
qualified_path = "camini::effects::models::damage_amt"
manifest_name = "ok-DamageAmt-1b34a805"

[[models.members]]
name = "creator"
type = "ContractAddress"
key = true

[[models.members]]
name = "amt"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x30e5082cb5a5e9277e834360394a93dd844adc266f8bd68b5d5378f456f52cb"
original_class_hash = "0x30e5082cb5a5e9277e834360394a93dd844adc266f8bd68b5d5378f456f52cb"
abi = "manifests/dev/deployment/abis/models/ok-Effect-cb9cbd0e.json"
tag = "ok-Effect"
qualified_path = "camini::effects::models::effect"
manifest_name = "ok-Effect-cb9cbd0e"

[[models.members]]
name = "effect_id"
type = "u32"
key = true

[[models.members]]
name = "contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
original_class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
abi = "manifests/dev/deployment/abis/models/ok-Game-57e3f47c.json"
tag = "ok-Game"
qualified_path = "camini::models::game::game"
manifest_name = "ok-Game-57e3f47c"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "teams"
type = "Array<u32>"
key = false

[[models.members]]
name = "turn_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "status"
type = "Status"
key = false

[[models.members]]
name = "phase"
type = "TurnPhase"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
original_class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
abi = "manifests/dev/deployment/abis/models/ok-Global-6bd7f442.json"
tag = "ok-Global"
qualified_path = "camini::models::global::global"
manifest_name = "ok-Global-6bd7f442"

[[models.members]]
name = "global_key"
type = "u8"
key = true

[[models.members]]
name = "pending_games"
type = "Array<u32>"
key = false

[[models.members]]
name = "damage_contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
original_class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
abi = "manifests/dev/deployment/abis/models/ok-Piece-828eb000.json"
tag = "ok-Piece"
qualified_path = "camini::models::piece::piece"
manifest_name = "ok-Piece-828eb000"

[[models.members]]
name = "piece_id"
type = "u32"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "piece_type"
type = "u32"
key = false

[[models.members]]
name = "location"
type = "Location"
key = false

[[models.members]]
name = "data"
type = "PieceData"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5307f55ac227d481336649271c87c1d4543f8bb2b30aebd8e0d871aa9beeb07"
original_class_hash = "0x5307f55ac227d481336649271c87c1d4543f8bb2b30aebd8e0d871aa9beeb07"
abi = "manifests/dev/deployment/abis/models/ok-PieceType-22a67789.json"
tag = "ok-PieceType"
qualified_path = "camini::models::piece::piece_type"
manifest_name = "ok-PieceType-22a67789"

[[models.members]]
name = "piece_type_id"
type = "u32"
key = true

[[models.members]]
name = "creator"
type = "ContractAddress"
key = false

[[models.members]]
name = "contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
original_class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
abi = "manifests/dev/deployment/abis/models/ok-Player-38fd8f17.json"
tag = "ok-Player"
qualified_path = "camini::models::player::player"
manifest_name = "ok-Player-38fd8f17"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "games"
type = "Array<u32>"
key = false

[[models.members]]
name = "pieces"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
original_class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
abi = "manifests/dev/deployment/abis/models/ok-Pool-a9992632.json"
tag = "ok-Pool"
qualified_path = "camini::models::pool::pool"
manifest_name = "ok-Pool-a9992632"

[[models.members]]
name = "pool_id"
type = "u32"
key = true

[[models.members]]
name = "piece_type_ids"
type = "Array<u32>"
key = false

[[models.members]]
name = "effect_type_ids"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x587a5a54f085893f0e9af9df744794be298c322bd3b8d3986f77488fc49222c"
original_class_hash = "0x587a5a54f085893f0e9af9df744794be298c322bd3b8d3986f77488fc49222c"
abi = "manifests/dev/deployment/abis/models/ok-Position-54881f2f.json"
tag = "ok-Position"
qualified_path = "camini::models::position::position"
manifest_name = "ok-Position-54881f2f"

[[models.members]]
name = "piece_id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1a48c25b88bb27ac5a689f9016fed98b2f408cb79f89cbb529e5f408546e4d6"
original_class_hash = "0x1a48c25b88bb27ac5a689f9016fed98b2f408cb79f89cbb529e5f408546e4d6"
abi = "manifests/dev/deployment/abis/models/ok-Team-718fa5ed.json"
tag = "ok-Team"
qualified_path = "camini::models::team::team"
manifest_name = "ok-Team-718fa5ed"

[[models.members]]
name = "team_id"
type = "u32"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "pieces"
type = "Array<u32>"
key = false

[[models.members]]
name = "location"
type = "Location"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x554e5c606a36b0e80b23a470e8498856a1d4924d50aabf406eab69fb1c14cf1"
original_class_hash = "0x554e5c606a36b0e80b23a470e8498856a1d4924d50aabf406eab69fb1c14cf1"
abi = "manifests/dev/deployment/abis/models/ok-Tile-fcb463a2.json"
tag = "ok-Tile"
qualified_path = "camini::models::position::tile"
manifest_name = "ok-Tile-fcb463a2"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = true

[[models.members]]
name = "piece"
type = "u32"
key = false
