[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x7837989e7bd026488ce42bcdd5ba1693d096a164f86514a4f8c16e21374d0a6"
transaction_hash = "0x17550480a041808db25c189027e2d9541e23e3ab5e4443b91a4e95c6ad009f3"
block_number = 3
seed = "camini"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x74333bf6b8345620c8ecde0536e76160df1d241786f28bbc5e0528a643219dd"
class_hash = "0x54d6bb9156747bca6d376182b328918a183868c690e6cf54063ffaa500a891e"
original_class_hash = "0x54d6bb9156747bca6d376182b328918a183868c690e6cf54063ffaa500a891e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-a-2fed5b94.json"
reads = []
writes = []
init_calldata = []
tag = "ok-a"
systems = []
manifest_name = "ok-a-2fed5b94"

[[contracts]]
kind = "DojoContract"
address = "0x70b7a453985439ff22b394ad024d646c2b76f70a7c750c6bdf852d3e6b0a9d7"
class_hash = "0x270d25746079005ba08c3bdb11e45d737d7dfc33499489c5c50378ef30e1c63"
original_class_hash = "0x270d25746079005ba08c3bdb11e45d737d7dfc33499489c5c50378ef30e1c63"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-arena-69309f5d.json"
reads = []
writes = [
    "ok-Game",
    "ok-Position",
    "ok-Global",
    "ok-Tile",
    "ok-Piece",
]
init_calldata = []
tag = "ok-arena"
systems = [
    "move",
    "attack",
]
manifest_name = "ok-arena-69309f5d"

[[contracts]]
kind = "DojoContract"
address = "0x2d0959006c4e6d218fb689ca699d27f5cbf6354e38245ca5e6353922cd4e394"
class_hash = "0x4ba01476d766a1ccaa5844c166590c4b54f1d4a0c264294461cf430fa694ca7"
original_class_hash = "0x4ba01476d766a1ccaa5844c166590c4b54f1d4a0c264294461cf430fa694ca7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-b-4ebf424d.json"
reads = []
writes = []
init_calldata = []
tag = "ok-b"
systems = []
manifest_name = "ok-b-4ebf424d"

[[contracts]]
kind = "DojoContract"
address = "0x123c11b48245dbc3dabad9d80ca74c3d89e1142abb43cf7a76fc728d224114f"
class_hash = "0x4b0140e65acfe0bea2b3199af86c92a7e0b806e9516cd08cfa84d72c6dff4f4"
original_class_hash = "0x4b0140e65acfe0bea2b3199af86c92a7e0b806e9516cd08cfa84d72c6dff4f4"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-damage-4ffd3b4e.json"
reads = []
writes = [
    "ok-Tile",
    "ok-Piece",
    "ok-DamageAmt",
]
init_calldata = []
tag = "ok-damage"
systems = ["set_amt"]
manifest_name = "ok-damage-4ffd3b4e"

[[contracts]]
kind = "DojoContract"
address = "0x127b2b0451d45130b81e714faa490df0d0fcf9ff3bc9ccc517eecabfb37818b"
class_hash = "0xede9f66c9a74f72de28d555ba6b903e8226686ac02df40b71966a7097fd7de"
original_class_hash = "0xede9f66c9a74f72de28d555ba6b903e8226686ac02df40b71966a7097fd7de"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-gacha-25121cda.json"
reads = []
writes = [
    "ok-Piece",
    "ok-Player",
]
init_calldata = []
tag = "ok-gacha"
systems = []
manifest_name = "ok-gacha-25121cda"

[[contracts]]
kind = "DojoContract"
address = "0x4a1c8334ed4aa89422ce0755d5b4a96d3a5076b45c811c98de30b502f47d0f7"
class_hash = "0x526e21233e932345eb62229d097f764d64c6d68f75eebb9565d3db1bc6cd450"
original_class_hash = "0x526e21233e932345eb62229d097f764d64c6d68f75eebb9565d3db1bc6cd450"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-gov-3de021f4.json"
reads = []
writes = [
    "ok-PieceType",
    "ok-Global",
    "ok-Effect",
    "ok-Pool",
]
init_calldata = []
tag = "ok-gov"
systems = [
    "add_piece",
    "set_damage_contract",
    "add_effect",
]
manifest_name = "ok-gov-3de021f4"

[[contracts]]
kind = "DojoContract"
address = "0xf96be03584ecbd076ddb4d5672773f632f05237cdc05b5dfd8db0dc49a24c9"
class_hash = "0x5a387431a9961749d0b740b2d42f294f97dd3bb0ce5d4b46cfaad9e4e1d5a1e"
original_class_hash = "0x5a387431a9961749d0b740b2d42f294f97dd3bb0ce5d4b46cfaad9e4e1d5a1e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-matchmaking-7ba13579.json"
reads = []
writes = [
    "ok-Global",
    "ok-Team",
    "ok-Player",
    "ok-Piece",
    "ok-Tile",
    "ok-Position",
]
init_calldata = []
tag = "ok-matchmaking"
systems = [
    "join_game",
    "start_game",
]
manifest_name = "ok-matchmaking-7ba13579"

[[contracts]]
kind = "DojoContract"
address = "0x6f148a93a31c327179dd78a0fb1695cbcd07c7e9cb9e5523f3fffc45c61c635"
class_hash = "0x6c295d046e9353f9b7b364ca42005d4768f63ee7b7d71b7f77d34fa5aef705b"
original_class_hash = "0x6c295d046e9353f9b7b364ca42005d4768f63ee7b7d71b7f77d34fa5aef705b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-teambuilder-5d16e22b.json"
reads = []
writes = [
    "ok-Team",
    "ok-Player",
    "ok-Piece",
    "ok-Tile",
    "ok-Position",
]
init_calldata = []
tag = "ok-teambuilder"
systems = [
    "add_piece_to_team",
    "remove_piece_from_team",
]
manifest_name = "ok-teambuilder-5d16e22b"

[[models]]
kind = "DojoModel"
class_hash = "0x5a971d3e8643648741e57e05681cd27ce2e6a33a6d081f6c3e9c91b10f7bf75"
original_class_hash = "0x5a971d3e8643648741e57e05681cd27ce2e6a33a6d081f6c3e9c91b10f7bf75"
abi = "manifests/dev/deployment/abis/models/ok-DamageAmt-1b34a805.json"
tag = "ok-DamageAmt"
manifest_name = "ok-DamageAmt-1b34a805"

[[models.members]]
name = "creator"
type = "ContractAddress"
key = true

[[models.members]]
name = "amt"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x30e5082cb5a5e9277e834360394a93dd844adc266f8bd68b5d5378f456f52cb"
original_class_hash = "0x30e5082cb5a5e9277e834360394a93dd844adc266f8bd68b5d5378f456f52cb"
abi = "manifests/dev/deployment/abis/models/ok-Effect-cb9cbd0e.json"
tag = "ok-Effect"
manifest_name = "ok-Effect-cb9cbd0e"

[[models.members]]
name = "effect_id"
type = "u32"
key = true

[[models.members]]
name = "contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
original_class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
abi = "manifests/dev/deployment/abis/models/ok-Game-57e3f47c.json"
tag = "ok-Game"
manifest_name = "ok-Game-57e3f47c"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "teams"
type = "Array<u32>"
key = false

[[models.members]]
name = "turn_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "status"
type = "Status"
key = false

[[models.members]]
name = "phase"
type = "TurnPhase"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
original_class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
abi = "manifests/dev/deployment/abis/models/ok-Global-6bd7f442.json"
tag = "ok-Global"
manifest_name = "ok-Global-6bd7f442"

[[models.members]]
name = "global_key"
type = "u8"
key = true

[[models.members]]
name = "pending_games"
type = "Array<u32>"
key = false

[[models.members]]
name = "damage_contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
original_class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
abi = "manifests/dev/deployment/abis/models/ok-Piece-828eb000.json"
tag = "ok-Piece"
manifest_name = "ok-Piece-828eb000"

[[models.members]]
name = "piece_id"
type = "u32"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "piece_type"
type = "u32"
key = false

[[models.members]]
name = "location"
type = "Location"
key = false

[[models.members]]
name = "data"
type = "PieceData"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5307f55ac227d481336649271c87c1d4543f8bb2b30aebd8e0d871aa9beeb07"
original_class_hash = "0x5307f55ac227d481336649271c87c1d4543f8bb2b30aebd8e0d871aa9beeb07"
abi = "manifests/dev/deployment/abis/models/ok-PieceType-22a67789.json"
tag = "ok-PieceType"
manifest_name = "ok-PieceType-22a67789"

[[models.members]]
name = "piece_type_id"
type = "u32"
key = true

[[models.members]]
name = "creator"
type = "ContractAddress"
key = false

[[models.members]]
name = "contract"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
original_class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
abi = "manifests/dev/deployment/abis/models/ok-Player-38fd8f17.json"
tag = "ok-Player"
manifest_name = "ok-Player-38fd8f17"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "games"
type = "Array<u32>"
key = false

[[models.members]]
name = "pieces"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
original_class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
abi = "manifests/dev/deployment/abis/models/ok-Pool-a9992632.json"
tag = "ok-Pool"
manifest_name = "ok-Pool-a9992632"

[[models.members]]
name = "pool_id"
type = "u32"
key = true

[[models.members]]
name = "piece_type_ids"
type = "Array<u32>"
key = false

[[models.members]]
name = "effect_type_ids"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x587a5a54f085893f0e9af9df744794be298c322bd3b8d3986f77488fc49222c"
original_class_hash = "0x587a5a54f085893f0e9af9df744794be298c322bd3b8d3986f77488fc49222c"
abi = "manifests/dev/deployment/abis/models/ok-Position-54881f2f.json"
tag = "ok-Position"
manifest_name = "ok-Position-54881f2f"

[[models.members]]
name = "piece_id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1a48c25b88bb27ac5a689f9016fed98b2f408cb79f89cbb529e5f408546e4d6"
original_class_hash = "0x1a48c25b88bb27ac5a689f9016fed98b2f408cb79f89cbb529e5f408546e4d6"
abi = "manifests/dev/deployment/abis/models/ok-Team-718fa5ed.json"
tag = "ok-Team"
manifest_name = "ok-Team-718fa5ed"

[[models.members]]
name = "team_id"
type = "u32"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "pieces"
type = "Array<u32>"
key = false

[[models.members]]
name = "location"
type = "Location"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x554e5c606a36b0e80b23a470e8498856a1d4924d50aabf406eab69fb1c14cf1"
original_class_hash = "0x554e5c606a36b0e80b23a470e8498856a1d4924d50aabf406eab69fb1c14cf1"
abi = "manifests/dev/deployment/abis/models/ok-Tile-fcb463a2.json"
tag = "ok-Tile"
manifest_name = "ok-Tile-fcb463a2"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = true

[[models.members]]
name = "piece"
type = "u32"
key = false
