kind = "DojoModel"
class_hash = "0xe4eb6805257ad9396c3519f3a5965adb163347bc222937b552f11f4148022"
original_class_hash = "0xe4eb6805257ad9396c3519f3a5965adb163347bc222937b552f11f4148022"
abi = "manifests/dev/base/abis/models/dojo_starter-Player-1cccb05d.json"
tag = "dojo_starter-Player"
manifest_name = "dojo_starter-Player-1cccb05d"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "games"
type = "Array<u32>"
key = false
