kind = "DojoModel"
class_hash = "0x7734638cca8314777e46671f6ebbfc6f1536115617814e135ec34cd589077fd"
original_class_hash = "0x7734638cca8314777e46671f6ebbfc6f1536115617814e135ec34cd589077fd"
abi = "manifests/dev/base/abis/models/dojo_starter-Position-2ac8b4c1.json"
tag = "dojo_starter-Position"
manifest_name = "dojo_starter-Position-2ac8b4c1"

[[members]]
name = "piece_id"
type = "u32"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "position"
type = "Vec2"
key = false
