kind = "DojoModel"
class_hash = "0x340aa684e329829c3a60e079430de8ab02ee3467042e78303f1af25b8b3d4d5"
original_class_hash = "0x340aa684e329829c3a60e079430de8ab02ee3467042e78303f1af25b8b3d4d5"
abi = "manifests/dev/base/abis/models/dojo_starter-Global-7d325fbd.json"
tag = "dojo_starter-Global"
manifest_name = "dojo_starter-Global-7d325fbd"

[[members]]
name = "global_key"
type = "u8"
key = true

[[members]]
name = "pending_games"
type = "Array<u32>"
key = false
