kind = "DojoModel"
class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
original_class_hash = "0x16f1728b06cb75def1a0ca1364f0b509fa272704ba6dca9e02cfe2e66a53b2a"
abi = "manifests/dev/base/abis/models/ok-Global-6bd7f442.json"
tag = "ok-Global"
qualified_path = "camini::models::global::global"
manifest_name = "ok-Global-6bd7f442"

[[members]]
name = "global_key"
type = "u8"
key = true

[[members]]
name = "pending_games"
type = "Array<u32>"
key = false

[[members]]
name = "damage_contract"
type = "ContractAddress"
key = false
