kind = "DojoModel"
class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
original_class_hash = "0x3d28f31ae2f98b4637bd950f1b99d0e8a7213b827c1a2d7eb2c541383d3aa5b"
abi = "manifests/dev/base/abis/models/ok-Game-57e3f47c.json"
tag = "ok-Game"
manifest_name = "ok-Game-57e3f47c"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[members]]
name = "teams"
type = "Array<u32>"
key = false

[[members]]
name = "turn_player"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "Status"
key = false

[[members]]
name = "phase"
type = "TurnPhase"
key = false
