kind = "DojoModel"
class_hash = "0xd05ed4eea100d31aa9e234299ffe22f6b2c36f96cbc063a8ceda936847663a"
original_class_hash = "0xd05ed4eea100d31aa9e234299ffe22f6b2c36f96cbc063a8ceda936847663a"
abi = "manifests/dev/base/abis/models/ok-Piece-828eb000.json"
tag = "ok-Piece"
manifest_name = "ok-Piece-828eb000"

[[members]]
name = "piece_id"
type = "u32"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "piece_type"
type = "u32"
key = false
