kind = "DojoModel"
class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
original_class_hash = "0x564e82dada165acb3f430ab3b2d96bb2eecd3508c806ad1a08b87ab28d5ccc0"
abi = "manifests/dev/base/abis/models/ok-Player-38fd8f17.json"
tag = "ok-Player"
qualified_path = "camini::models::player::player"
manifest_name = "ok-Player-38fd8f17"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "games"
type = "Array<u32>"
key = false

[[members]]
name = "pieces"
type = "Array<u32>"
key = false
