kind = "DojoModel"
class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
original_class_hash = "0x47acdf8f97ab48431c76a4cf3f537ad0ff56c341640f0713e8acbcf38173632"
abi = "manifests/dev/base/abis/models/ok-Piece-828eb000.json"
tag = "ok-Piece"
manifest_name = "ok-Piece-828eb000"

[[members]]
name = "piece_id"
type = "u32"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "piece_type"
type = "u32"
key = false

[[members]]
name = "location"
type = "Location"
key = false

[[members]]
name = "data"
type = "PieceData"
key = false
