kind = "DojoModel"
class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
original_class_hash = "0x2f784b7327699c45a9e819cd9df688149dc1142e788071dd742e561ebd40df5"
abi = "manifests/dev/base/abis/models/ok-Pool-a9992632.json"
tag = "ok-Pool"
manifest_name = "ok-Pool-a9992632"

[[members]]
name = "pool_id"
type = "u32"
key = true

[[members]]
name = "piece_type_ids"
type = "Array<u32>"
key = false

[[members]]
name = "effect_type_ids"
type = "Array<u32>"
key = false
