kind = "DojoContract"
class_hash = "0x3ac84349e57bb542c90a1ff11e9cc0f427978a252ea789f016d3f78194ec48"
original_class_hash = "0x3ac84349e57bb542c90a1ff11e9cc0f427978a252ea789f016d3f78194ec48"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-actions"
systems = []
manifest_name = "dojo_starter-actions-7a1c7102"
