kind = "DojoContract"
class_hash = "0x7f6b484886231d0af670926b320be341b9e9bbef4fce099aa26f44ffa1e0ff3"
original_class_hash = "0x7f6b484886231d0af670926b320be341b9e9bbef4fce099aa26f44ffa1e0ff3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-arena-69309f5d.json"
reads = []
writes = []
init_calldata = []
tag = "ok-arena"
systems = ["move"]
manifest_name = "ok-arena-69309f5d"
