kind = "DojoContract"
class_hash = "0x270d25746079005ba08c3bdb11e45d737d7dfc33499489c5c50378ef30e1c63"
original_class_hash = "0x270d25746079005ba08c3bdb11e45d737d7dfc33499489c5c50378ef30e1c63"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-arena-69309f5d.json"
reads = []
writes = []
init_calldata = []
tag = "ok-arena"
systems = [
    "move",
    "attack",
]
manifest_name = "ok-arena-69309f5d"
