kind = "DojoContract"
class_hash = "0xede9f66c9a74f72de28d555ba6b903e8226686ac02df40b71966a7097fd7de"
original_class_hash = "0xede9f66c9a74f72de28d555ba6b903e8226686ac02df40b71966a7097fd7de"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-gacha-25121cda.json"
reads = []
writes = []
init_calldata = []
tag = "ok-gacha"
systems = []
manifest_name = "ok-gacha-25121cda"
