kind = "DojoContract"
class_hash = "0x262cc7fce561d7e3d1889f2a6e9ee74e5ec8fa6f249564a6269b29d41dbc332"
original_class_hash = "0x262cc7fce561d7e3d1889f2a6e9ee74e5ec8fa6f249564a6269b29d41dbc332"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-Gov-4e872671.json"
reads = []
writes = []
init_calldata = []
tag = "ok-Gov"
systems = ["add_piece"]
manifest_name = "ok-Gov-4e872671"
