kind = "DojoContract"
class_hash = "0x169940e0549934076f738a6558ba63cd48ac376329e553f8606673da1f200b"
original_class_hash = "0x169940e0549934076f738a6558ba63cd48ac376329e553f8606673da1f200b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-gov-3de021f4.json"
reads = []
writes = []
init_calldata = []
tag = "ok-gov"
systems = [
    "add_piece",
    "set_damage_contract",
    "add_effect",
]
manifest_name = "ok-gov-3de021f4"
