kind = "DojoContract"
class_hash = "0x526e21233e932345eb62229d097f764d64c6d68f75eebb9565d3db1bc6cd450"
original_class_hash = "0x526e21233e932345eb62229d097f764d64c6d68f75eebb9565d3db1bc6cd450"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-gov-3de021f4.json"
reads = []
writes = []
init_calldata = []
tag = "ok-gov"
systems = [
    "add_piece",
    "set_damage_contract",
    "add_effect",
]
manifest_name = "ok-gov-3de021f4"
