kind = "DojoContract"
class_hash = "0x6c295d046e9353f9b7b364ca42005d4768f63ee7b7d71b7f77d34fa5aef705b"
original_class_hash = "0x6c295d046e9353f9b7b364ca42005d4768f63ee7b7d71b7f77d34fa5aef705b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-teambuilder-5d16e22b.json"
reads = []
writes = []
init_calldata = []
tag = "ok-teambuilder"
systems = [
    "add_piece_to_team",
    "remove_piece_from_team",
]
manifest_name = "ok-teambuilder-5d16e22b"
