kind = "DojoContract"
class_hash = "0x683bb297ec1c94d31f47114247f9a9398f672444da8286ece0530975bfb5731"
original_class_hash = "0x683bb297ec1c94d31f47114247f9a9398f672444da8286ece0530975bfb5731"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-teambuilder-5d16e22b.json"
reads = []
writes = []
init_calldata = []
tag = "ok-teambuilder"
systems = [
    "add_piece_to_team",
    "remove_piece_from_team",
]
manifest_name = "ok-teambuilder-5d16e22b"
